### ISSUE TITLE
Strategy for auto-updating Docker image on game update

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#5]
We should consider finding a strategy to auto-update the Docker image, when a game update is released - if possible in a way, that doesn't introduce bugs or other problems with the image. A new release of the image should be a patch release for the last minor release or maybe all minor releases.

**Comment by BraisGabin** [comment]
I was thinking about this. Update all our realeses is easy for us. And we are not going to add any Break Change because we are not changing the Dockfile or the entrypoint.

But Klei can make a Breaking Change in a game update. It's unlikely but it can happen. Must we be carefull about this?

Klei usually launch a beta an then realese it. We can have two images the beta and the _stable_. Something like `v0.3.0` and `v0.3.0-beta`. If something breaks at beta is not such a big deal. And we are going to get red alarms from our users telling us that it didn't work. We can fix it before this problem appears at the no beta version.

And as I said before, I think that Klei is not going to make a lot of breaking changes.

**Comment by thasmo** [comment]
Ye, we should have stable and beta images; planning in #22.

For automatically rebuilding images we need a separate application running on a server, which checks for updates periodically and triggers the rebuilding of the images.

**Comment by BraisGabin** [comment]
Milestone `v1.0`? We need to launch the stables version with this but we don't need it before that.

**Comment by thasmo** [comment]
Some thoughts.

In theory, when a new game update is released, **all** existing tags must be rebuilt, which can be a lot and this brings up an important question - and you've mentioned it already.

What if Klei changes something major in the game like file names or directory structures? If we blindly rebuild all images, we may break **all** images. With _break_ I mean, that building _may_ succeed, for whatever reason, but people will update their images and creating containers will fail.

This is a major concern, which is a strong argument for not updating the images at all. If people use old tags/images, they need to accept that it will potentionally download some, or a lot of game updates when creating a new container. (Which also can break the containers, if you think about it.)

**Comment by BraisGabin** [comment]
The rebuild work is made by travis and/or Docker Hub so... it's not a big problem. And we don't want to waste their resources, if we do all that builds will be because we need them.

The Klei BC are a problem. We need to define how to deal with them and, probably, write that in the same place as #21. Some thoughts:
- Which major realeses are we going to support? I thinkg that we are small. If we launcha new one we stop the support to the last version.
- If Klei adds a BC we'll need to increase the major version. Has this sense?
- `latest` and `next` _always_ update automaticaly with the game (if the tests are green).
- We _must_ trust the tests. If we have a false positive we must fix it. This is as important as fix the bug itself.
- Can we update the images manually? I mean, after some kind of inspection? Only the last major realese. We don't compromise to do it, but it's something that we can do. The users may know that even a fix realese can change, but if they do is because one of the collaborators test it. I don't like the no-updated images. It reminds me the [Android fragmentation](http://developer.android.com/intl/es/about/dashboards/index.html#Platform).

Is posible to connect to an outdated server? Are we just hidding the head? Does an outdated version work for someone?

**Comment by thasmo** [comment]
Maybe we should only rebuild the latest minor version. Currently `0.5.0` is the latest version, so this tags/images should be rebuilt:
- 0.5.0
- 0.5
- 0
- latest
- next

For example, if we would have `1.2.5` as the current version, these tags/images would be rebuilt:
- 1.2.5
- 1.2
- 1
- latest
- next

All prior versions (1.1, 1.1.x, 1.0, 1.0.x, 0.x, etc.) will not be rebuilt to download new game files.

About BC changes Klei introduces; I think we can't do anything about it. As soon as we figure out that there's a problem, we release a new minor version (1.2.x -> 1.3.0) which fixes the problems and future updates from Klei (as mentioned above) will only update the new minor version (1.3.0, 1.3, 1, latest, next) but not 1.2, etc.

**Comment by thasmo** [comment]
I thought about this and I think it's totally sufficient to rebuild the images once a day, in the night. We need to ensure that `dstacademy/steamcmd` gets rebuilt first and `dstacademy/dontstarvetogether` afterwards. We actually don't need to rebuild the images in the moment a new game update is released, I believe.

**Comment by BraisGabin** [comment]
I think that you are right.

**Comment by BraisGabin** [comment]
Any new idea about this?

**Comment by BraisGabin** [comment]
Ok, it seems that docker hub implemented webhooks: https://docs.docker.com/docker-hub/builds/#remote-build-triggers

With this we can create a chron job in a server and run `dst-server check` every hour. If it fails, we call the triger. This way we ensure that we always have the most recent image.

Other option would be use ifttt but klei doesn't have a feed with their updates...

We can do the same with steamcmd.

What do you think? I can create the script. And then we can decide where run the script. I can run it in my server if you want. Or we can run in yours if you prefer.

The only "problem" is that I don't have access to the dst-academy docker hub account. So you must setup the webhooks.

**Comment by BraisGabin** [comment]
What do you think about this @thasmo?
